;; 追加のキーマップ
(global-set-key (kbd "ESC M-%") 'query-replace-regexp)
(global-set-key (kbd "ESC M-:") 'eval-region)
(global-set-key (kbd "ESC M-<") 'beginning-of-buffer-other-window)
(global-set-key (kbd "C-x 4 s") 'reishi-open-term-other-window)
(global-set-key (kbd "C-x C-p") 'reishi-other-window-backward)
(global-set-key (kbd "C-x C-n") 'other-window)
(global-set-key (kbd "C-x C-q") 'view-mode)
(global-set-key (kbd "C-x l")   'goto-line)
(global-set-key (kbd "C-h") 'backward-delete-char)
(global-set-key (kbd "M-p")     'backward-paragraph)
(global-set-key (kbd "M-n")     'forward-paragraph)
(global-set-key [C-tab]         'bury-buffer)
(global-set-key [delete]        'backward-delete-char)
(global-set-key [home]          'beginning-of-buffer)
(global-set-key [end]           'end-of-buffer)
;(display-time)
;(display-battery)

;windowmove
(windmove-default-keybindings)
(setq windmove-wrap-around t)
;; (global-set-key (quote [kp-8]) (quote windmove-up))
;; (global-set-key (quote [kp-2]) (quote windmove-down))
;; (global-set-key (quote [kp-6]) (quote windmove-right))
;; (global-set-key (quote [kp-4]) (quote windmove-left))
(global-set-key (kbd "C-M-f") 'windmove-left)
(global-set-key (kbd "C-M-b") 'windmove-right)
(global-set-key (kbd "C-M-p") 'windmove-up)
(global-set-key (kbd "C-M-n") 'windmove-down)
