(require 'key-combo)
(key-combo-mode 1)
(setq key-combo-common-default
      '((","  . ", ")
        ("="  . (" = " " == " " === " ))
        ("=>" . " => ")
        ("=~" . " =~ ")
        ("=*" . " =* ")
        ("+"  . (" + " "++"))
        ("+=" . " += ")
        ("-"  . (" - " "--"))
        ("-=" . " -= ")
        ("->" . "->")
        (">"  . (key-combo-execute-original " >> "))
        (">=" . " >= ")
        (">>=" . " >>= ")
        ;;         ("%"  . " % ")
        ("%="  . " %= ")
        ("^"  . " ^ ")
        ("^="  . " ^= ")
        ("!" . key-combo-execute-original)
        ("!="  . " != " )
        ("!==" . " !== ")
        ("!~" . " !~ ")
        ("~" . key-combo-execute-original)
        ("&"  . (" & " " && "))
        ("&=" . " &= ")
        ("&&=" . " &&= ")
        ("*"  . " * " )
        ("*="  . " *= " )
        ("**"  . "**" )
        ("**=" . " **=" )
        ("<" . (key-combo-execute-original " << " " <= "))
        ("<=>" . " <=> ")
        ("<=" . " <= ")
        ("<<=" . " <<= ")
        ("<-" . " <- ")
        ("<!" . "<!-- `!!' -->")
        ("|"  . (" | " " || "))
        ("|=" . " |= ")
        ("||=" . " ||= ")
        ("/" . (key-combo-execute-original " // "))
        ("/ SPC" . " / ")
        ("//=" . " //= ")
        ("/=" . " /= ")
        ("*/" . "*/")
        ("/*" . "/* `!!' */")
        ("/* RET" . "/*\n`!!'\n*/")
        ("{" . (key-combo-execute-original))
        ("{ RET" . "{\n`!!'\n}\n")
        ))
(key-combo-load-default)
(key-combo-define-hook key-combo-common-mode-hooks
                       'key-combo-common-load-default
                       key-combo-common-default)
